import type { Metadata } from "next";
// Import only Paytone One
import { Paytone_One } from "next/font/google"; 
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";
import { CssBaseline } from "@mui/material";
import Header from "@/components/Header";

// Configure Paytone One
const paytoneOne = Paytone_One({
  weight: ['400'], // Paytone One only has one weight
  subsets: ['vietnamese', 'latin'], // Include Vietnamese subset
  display: 'swap',
  variable: '--font-paytone-one',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <ThemeProvider theme={theme}>
        <CssBaseline />
        {/* Apply only the Paytone One font variable */}
        <body
          className={`${paytoneOne.variable} antialiased`}
        >
          <Header />
          <main>{children}</main>
        </body>
      </ThemeProvider>
    </html>
  );
}